### ISSUE TITLE
Change mocks loading status message level to debug

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoftgraph/msgraph-developer-proxy#175]
The mocks loading status message https://github.com/microsoftgraph/msgraph-developer-proxy/blob/4fb432366f9063b772f8fbb5bfd34f7b8da999be/msgraph-developer-proxy-plugins/MockResponses/MockResponsesLoader.cs#L34 feels more like a debug- than info-level message. I suggest that we change its logging level to debug.

**Comment by garrytrinder** [comment]
I agree that it does, however we do need to provide some indication the user that responses have been loaded IMO, so we should think about a friendly way to inform them.

**Comment by waldekmastykarz** [comment]
Shouldn't we align this with loading plugins which we currently don't communicate? I think both settings are similar in nature and we should align how we communicate about them.

**Comment by garrytrinder** [comment]
We should, good point.

Rather than thinking of specific cases, maybe its worth considering what information we should display and how we should display it when the proxy starts.

If you run the proxy with defaults, this is what you see...

![image](https://user-images.githubusercontent.com/11563347/234621388-ebb3db6d-01a4-49b0-b9e4-8872a8750877.png)

I think we can make this much more interesting and informative.

Thinking of some of the events that happen on start-up.

 - A global proxy is started (Windows only)
 - Responses file is loaded
 - Plugins are loaded
 - URLs are watched
 - Errors file is loaded

Shall we create a UI improvements issue for when the proxy runs to gather some ideas?

**Comment by waldekmastykarz** [comment]
> Shall we create a UI improvements issue for when the proxy runs to gather some ideas?

Let's do that indeed. Let's think what's necessary as a confirmation vs. what we could skip because it's already expressed in the config. Let's close this issue and pick up from the new one that's broader.
