### ISSUE TITLE
Extend the proxy to support URLs other than Graph, eg. SharePoint REST/CSOM, MS Search, etc.

### ISSUE THREAD

**Issue by jansenbe** [microsoftgraph/msgraph-developer-proxy#54]
Today when it comes to SharePoint/OneDrive applications we still see a many applications that take aa hybrid approach in which they use Graph for core scenarios but fall back to either SharePoint REST or SharePoint CSOM for the operations that covered via Graph APIs. 

In order to test such applications having support for SharePoint REST/CSOM would really help. The proxy could dynamically detect SharePoint URLs being hit (*.sharepoint.com, *.sharepoint.us,...) and that would work for the majority of cases. For vanity URL tenants ideally there's an option to specify the wildcard URL on which the proxy will take action.

This is a great tool to help developers, looking forward to see it's scope widen by supporting SharePoint REST/CSOM calls.

**Comment by waldekmastykarz** [comment]
@gavinbarron that would require us to extend the list of domains, with SharePoint domains across the different clouds and allow using wildcards, correct?

**Comment by gavinbarron** [comment]
@waldekmastykarz yes, it would require a bit of re-work on how we determine if a request is passed to the proxy behaviors or passed through. 

We should be able to use a regex or some other pattern match for this. 

As to extending the "cloud" being proxied, that should be reasonably straightforward.

**Comment by waldekmastykarz** [comment]
Specifically to support SharePoint URLs, what if we'd use `.EndsWith()` rather than equals when we come across a URL with an asterisk? That should be faster than converting a string to a regex and matching it against every URL.

**Comment by wobba** [comment]
There are other "internal" API REST URL's in M365 which would benefit from this proxy in terms of 1p dev `*.office.com` based ones.

**Comment by waldekmastykarz** [comment]
Great suggestion @wobba and thank you for making us aware of other URLs for which the Proxy would be relevant

**Comment by gavinbarron** [comment]
I think that based on the feedback from @wobba we should be looking at pattern matching for the domains to be intercepted rather than a `.EndsWith()`

**Comment by waldekmastykarz** [comment]
Since we'll be looking at intercepting requests from multiple domains, I suggest that we move away from the cloud configuration, and instead specify an array of host names that we intercept. By default, we'd include all known URLs (eg. Graph and SharePoint URLs across all clouds). A host name can be a complete string or contain wildcards, like `df.*.office.com`. We'd update the URL matching logic in https://github.com/microsoftgraph/msgraph-developer-proxy/blob/e27ee81b21ffe630908d6814b7d1acdf469ea549/msgraph-developer-proxy/ChaosEngine.cs#L216 so that it compares the host against the array of hosts defined in config. For each host we'd run the comparison: if the host doesn't contain a wildcard, we'd run an equals comparison. If it does, we'd run `Regex.Escape` on the host name, to escape special regex characters and then replace `\*`, with `.*` so that it's properly matched as a wildcard in regex. To speed matching up, we'd prepare regexes when starting the proxy and build them in a compiled mode, so that they're built only once, rather than on each URL matching. This also means, that for mock responses, we need to use absolute URLs, because we can't tell which host name to add. What do you think @gavinbarron?

**Comment by sebastienlevert** [comment]
I just added the specs in #70. Reviews are welcome!
