### ISSUE TITLE
Enhancement: Prevent adding the same URL to watch multiple times

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoftgraph/msgraph-developer-proxy#98]
Right now, it's possible to add the same URL to watch multiple times.

While we prevent this for hosts: https://github.com/microsoftgraph/msgraph-developer-proxy/blob/05e8a5bbf682586e82483fd9d1bd295f803e2e92/msgraph-developer-proxy/ChaosEngine.cs#L200-L202

we don't check for it for URLs: https://github.com/microsoftgraph/msgraph-developer-proxy/blob/05e8a5bbf682586e82483fd9d1bd295f803e2e92/msgraph-developer-proxy/ChaosEngine.cs#L184

Tracking the same URLs adds to processing time and we should avoid it so that we can process URLs as quickly as possible.

Originally reported by @jansenbe

**Comment by gavinbarron** [comment]
@waldekmastykarz I ran into this when I was experimenting with the implementation of the plugin system.

My solution, which I've not had a chance to test when duplicates exist in the top-level list of urls, is to use an `ISet<Regex>` internally to hold the compiled Regexs which prevents duplicates and is still enumerable. This is populated while the plugins are loaded so that we have both per-plugin lists and a top level list which is the distinct set of Regex for which the proxy needs to decrypt SSL traffic.

Check it out in the rough form https://github.com/microsoftgraph/msgraph-developer-proxy/blob/00effd07d944890de0907190a534a56292169720/msgraph-developer-proxy/PluginLoader.cs#L22

**Comment by waldekmastykarz** [comment]
Since we've merged the new plugins architecture, is still an issue or is it already fixed in the code you've added @gavinbarron and we can consider this issue as solved?

**Comment by gavinbarron** [comment]
Closed in #99
